services:
  mongodb:
    image: mongo:latest
    container_name: nextjs-mongodb
    command: mongod --replSet rs0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      # - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - app_network

# volumes:
#   mongodb_data:
#     driver: local

networks:
  app_network:
    driver: bridge