services:
  mongodb:
    image: mongo:latest
    container_name: nextjs-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge