name: Clone and Setup
on:
  workflow_dispatch:

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PEM }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            REPO_DIR="/path/to/repo"
            [ -d "$REPO_DIR" ] && rm -rf "$REPO_DIR"
            git clone ${{ secrets.REPO_URL }} "$REPO_DIR"
            cd "$REPO_DIR"
            
            # Create .env file from secrets
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            
            npm install
