name: App Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Generator App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            echo "STARTING Deployment"
            [ -d "deeplink-resolver-server" ] && sudo rm -rf "deeplink-resolver-server"
            sudo git clone https://github.com/abhik-wil/deeplink-resolver-server.git
            cd deeplink-resolver-server/deeplink-generator

            sudo rm -f .env
            sudo rm -f docker-compose.yml

            # Create backend .env file
            sudo cat > .env << EOL
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            EOL


            sudo cp docker-compose.dev.yml docker-compose.yml
            sudo docker compose up ondc_deep_link_app -d --build
            sudo docker system prune -f
            sudo systemctl restart nginx

