name: App Deployment
on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Generator App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            cd deeplink-resolver-server
            
            git pull origin master
            cd deeplink-generator

            rm -f .env
            rm -f docker-compose.yml


            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env


            cp docker-compose.dev.yml docker-compose.yml
            sudo docker-compose up ondc_deep_link_app -d --build
            sudo docker system prune -f
            sudo systemctl restart nginx

