name: Clone and Setup
on:
  workflow_dispatch:

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            [ -d "deeplink-resolver-server" ] && rm -rf "deeplink-resolver-server"
            git clone git@github.com:abhik-wil/deeplink-resolver-server.git
            cd deeplink-resolver-server/deeplink-generator
            
            # Create .env file from secrets
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            
            npm install
