name: Database Operations
on:
  workflow_dispatch:

jobs:
  db-reset-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Generator DB Operations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            cd deeplink-resolver-server/deeplink-generator

            echo "DB Teardown and Restart"
            sudo docker compose down ondc_deep_link_db
            sudo docker rm -f ondc_deep_link_db
            sudo docker compose up -d ondc_deep_link_db
            
            sleep 10
            sudo docker run --rm \
              --network ondc_deep_link \
              -v $(pwd)/prisma:/app/prisma \
              -v $(pwd)/seeding:/app/seeding \
              node:23-alpine \
              sh -c "cd /app && npm install && npx prisma generate && npx prisma migrate deploy && node seeding/seed.js"

