name: Database Operations
on:
  workflow_dispatch:

jobs:
  db-reset-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Generator DB Operations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            cd deeplink-resolver-server/deeplink-generator
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            source ~/.bashrc
            
            nvm use --lts
            node -v
            npm -v

            echo "STARTING Dep Installation"
            sudo npm i --force

            echo "DB Teardown and Restart"
            sudo docker compose down ondc_deep_link_db
            sudo docker rm -f ondc_deep_link_db
            sudo docker compose up -d ondc_deep_link_db
            
            sleep 10

            npx prisma migrate reset
